### ISSUE TITLE
Publish ROS topics to VR

### ISSUE THREAD

**Issue by erwang01** [immersive-command-system/isaacs_server#17]
Need to publish GPS coords for drone to move in VR. this is a highish priority.

**Comment by erwang01** [comment]
I believe this is to be done straight from the ROS node on the Drone.
@immersive-command-system/drone can you guys confirm?

**Comment by DragonKyro** [comment]
Yeah, probably drone publishes to server and vr subscribes.  Operator doesn't need to process gps coords does it? Unless any transformations should be done on operator.

**Comment by DragonKyro** [comment]
Should be done on the drone side.  Drone should register topics with the server and publish its gps coords.  VR can then query for topics and subscribe to gps coords. No work needs to be done on server
