### ISSUE TITLE
Register Drone Service Test Does not end.

### ISSUE THREAD

**Issue by erwang01** [immersive-command-system/isaacs_server#18]
The register drone service test does not think that the register drone service ever responded (it just hangs there on line 12 linked below). However, the operator.py recognizes the drone has been registered and responds fine to an all_available_drones service call.

https://github.com/immersive-command-system/isaacs_server/blob/6e276db3e5692d4e98c8c3defb871ec5cde02e3a/src/service_test/register_drone.py#L12

**Comment by DragonKyro** [comment]
Works now using test cases.  Sometimes service calls hang randomly.  I think it has something to do with calling multiple services one after the other.
