### ISSUE TITLE
Drone implementation tests

### ISSUE THREAD

**Issue by erwang01** [immersive-command-system/isaacs_server#19]
Add test to see if the drone.py implementations provide the proper response fields, including the new `id` field.

_Originally posted by @erwang01 in https://github.com/immersive-command-system/isaacs_server/pull/9#discussion_r567296534_

**Comment by DragonKyro** [comment]
Tested success field.  Need to add id fields.

**Comment by DragonKyro** [comment]
Checks for id now.
