### ISSUE TITLE
Shutdown Drone Service Type

### ISSUE THREAD

**Issue by erwang01** [immersive-command-system/isaacs_server#20]
If we link topics to the drone object already, does the user really need to report publishes?

_Originally posted by @erwang01 in https://github.com/immersive-command-system/isaacs_server/pull/9#r558997339_

**Comment by DragonKyro** [comment]
Publishes is needed because we're reusing a service definition.  Akhil says requesting publishes from the vr side shouldn't be too difficult, so keeping current implementation.  Closing issue.
