### ISSUE TITLE
Response Variable Override

### ISSUE THREAD

**Issue by erwang01** [immersive-command-system/isaacs_server#22]
In Operator.py, our service calls are passed in a `response` object that we populate. When we say `response = func()`, we will remap the `response` variable to the return value of func(). 

See if this breaks our program. My hunch is that the response returned as a result will be empty / not contain the final values that we want. (potentially containing failure codes due to default assignments)

Example:
https://github.com/immersive-command-system/isaacs_server/blob/72cd8dad09452e4e5a0b51d10d7194082350847f/src/operator.py#L151

**Comment by DragonKyro** [comment]
Overwriting response variables doesn't seem to work.  I'm guessing that ROS looks at a specific dictionary instance.  Changed operator to fix this.
