### ISSUE TITLE
Drone.py return types.

### ISSUE THREAD

**Issue by erwang01** [immersive-command-system/isaacs_server#24]
This is in both drone subclasses

Return type of many service call functions should be :            dictionary {
                success: boolean
                message: descriptive string
            } 

per drone.py

_Originally posted by @erwang01 in https://github.com/immersive-command-system/isaacs_server/pull/9#discussion_r567334273_

**Comment by DragonKyro** [comment]
Where? What's the issue?

**Comment by erwang01** [comment]
In DJIMatrice: our service calls simply return the result passed back by the DJI service call: https://github.com/immersive-command-system/isaacs_server/blob/1b802e57119c95bdea2768e47fa63db373617236/src/djimatrice_drone.py#L51

However, in drone.py we say that it should have a success boolean and a message string.

**Comment by DragonKyro** [comment]
result is a dictionary with success and message fields
