### ISSUE TITLE
Drone Interface Base Class

### ISSUE THREAD

**Issue by erwang01** [immersive-command-system/isaacs_server#6]
Implement a Drone Interface Base Class. This should be extendable and each child class can be a different ROS node or smtg.

**Comment by erwang01** [comment]
Lets us ROSLibPy.

See the API documentation / Create any as needed.

**Comment by erwang01** [comment]
Create the base class. 

Basically all you want is to just define the functions that all Drones should have. These are detailed out onto the [API docs](https://docs.google.com/document/d/1g3dKYSgtFYrp6Fd4SA6JV8K353C8m3OqXH_cyjhj9-0/edit) under the Drone to server section. 

We want them to have  just the message signature. The method body can be as simple as return False or Fatal for the base class.

**Comment by varunsaran** [comment]
Added definitions for all abstract methods of the base Drone class.
TODO: message signatures

**Comment by DragonKyro** [comment]
Completed method comments with parameters and return values
